In [140]:
import pandas as pd
import datetime 
from datetime import timedelta
empty_dict = {}
l = []
print(empty_dict)

{}

In [6]:
df = pd.read_csv('./test_data.csv') 
df.head()

        delivery_start            timestamp  wind forecast in MW
0  2018-12-20 00:00:00  2018-12-20 00:00:00                12815
1  2018-12-20 00:00:00  2018-12-19 23:45:00                12629
2  2018-12-20 00:00:00  2018-12-19 23:30:00                12546
3  2018-12-20 00:00:00  2018-12-19 23:15:00                12654
4  2018-12-20 00:00:00  2018-12-19 23:00:00                12741

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368927 entries, 0 to 368926
Data columns (total 3 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   delivery_start       368927 non-null  object
 1   timestamp            368927 non-null  object
 2   wind forecast in MW  368927 non-null  int64
dtypes: int64(1), object(2)
memory usage: 8.4+ MB

In [8]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [9]:
df['timestamp'].dt.time

0         00:00:00
1         23:45:00
2         23:30:00
3         23:15:00
4         23:00:00
            ...
368922    01:15:00
368923    01:00:00
368924    00:45:00
368925    00:30:00
368926    00:15:00
Name: timestamp, Length: 368927, dtype: object

In [10]:
df.head()

        delivery_start           timestamp  wind forecast in MW
0  2018-12-20 00:00:00 2018-12-20 00:00:00                12815
1  2018-12-20 00:00:00 2018-12-19 23:45:00                12629
2  2018-12-20 00:00:00 2018-12-19 23:30:00                12546
3  2018-12-20 00:00:00 2018-12-19 23:15:00                12654
4  2018-12-20 00:00:00 2018-12-19 23:00:00                12741

In [11]:
df['timestamp'].dt.date

0         2018-12-20
1         2018-12-19
2         2018-12-19
3         2018-12-19
4         2018-12-19
             ...
368922    2018-12-17
368923    2018-12-17
368924    2018-12-17
368925    2018-12-17
368926    2018-12-17
Name: timestamp, Length: 368927, dtype: object

In [12]:
df[timestamp > 11:00:00]

NameError: name 'timestamp' is not defined

In [13]:
df['timestamp' > 11:00:00]

TypeError: '>' not supported between instances of 'str' and 'int'

In [14]:
df['timestamp'.int() > 11:00:00]

AttributeError: 'str' object has no attribute 'int'

In [15]:
def su(x,y):
    return x-y

In [39]:
ex = datetime.datetime.strptime('11:30AM', '%I:%M%p') 
print(ex.time()) 
new_day = datetime.datetime.strptime('12:00AM', '%I:%M%p')  
print(new_day.time())  
new_day2 = datetime.datetime.strptime('12:15AM', '%I:%M%p')

11:30:00
00:00:00

In [17]:
df['timestamp'].dt.date

0         2018-12-20
1         2018-12-19
2         2018-12-19
3         2018-12-19
4         2018-12-19
             ...
368922    2018-12-17
368923    2018-12-17
368924    2018-12-17
368925    2018-12-17
368926    2018-12-17
Name: timestamp, Length: 368927, dtype: object

In [18]:
df['delivery_start'] = pd.to_datetime(df['delivery_start']) 
df['delivery_start'].dt.date

0         2018-12-20
1         2018-12-20
2         2018-12-20
3         2018-12-20
4         2018-12-20
             ...
368922    2018-12-25
368923    2018-12-25
368924    2018-12-25
368925    2018-12-25
368926    2018-12-25
Name: delivery_start, Length: 368927, dtype: object

In [19]:
remove = ['delivery_start','timestamp','wind forecast in MW'] 
val = pd.DataFrame()
val = su(df['delivery_start'].dt.date ,df['timestamp'].dt.date) 
print(val)

0        0 days
1        1 days
2        1 days
3        1 days
4        1 days
          ...
368922   8 days
368923   8 days
368924   8 days
368925   8 days
368926   8 days
Length: 368927, dtype: timedelta64[ns]

In [20]:
%%time
condition1 = ((df['delivery_start'].dt.date - df['timestamp'].dt.date) == '1 days') & (df['timestamp'].dt.time >= ex.time())   
condition2 = ((df['delivery_start'].dt.date - df['timestamp'].dt.date) == '0 days')

CPU times: user 951 ms, sys: 15.4 ms, total: 967 ms
Wall time: 965 ms

In [21]:
%%time
df = df[condition1|condition2]  
df.head(200)

CPU times: user 8.96 ms, sys: 6.23 ms, total: 15.2 ms
Wall time: 12.6 ms

          delivery_start           timestamp  wind forecast in MW
0    2018-12-20 00:00:00 2018-12-20 00:00:00                12815
1    2018-12-20 00:00:00 2018-12-19 23:45:00                12629
2    2018-12-20 00:00:00 2018-12-19 23:30:00                12546
3    2018-12-20 00:00:00 2018-12-19 23:15:00                12654
4    2018-12-20 00:00:00 2018-12-19 23:00:00                12741
...                  ...                 ...                  ...
2343 2018-12-20 00:45:00 2018-12-19 14:00:00                12804
2344 2018-12-20 00:45:00 2018-12-19 13:45:00                12807
2345 2018-12-20 00:45:00 2018-12-19 13:30:00                12872
2346 2018-12-20 00:45:00 2018-12-19 13:15:00                12815
2347 2018-12-20 00:45:00 2018-12-19 13:00:00                12881

[200 rows x 3 columns]

In [22]:
df.to_csv("./new.csv")

In [144]:
def conv(x,y,z):  
    if x.time() == ex.time():
        empty_dict[(str(y.date()), str(y.time()))] = z

In [145]:
%%time 
df.apply(lambda x: conv(x['timestamp'],x['delivery_start'],x['wind forecast in MW']), axis=1)

CPU times: user 518 ms, sys: 9.27 ms, total: 527 ms
Wall time: 524 ms

0         None
1         None
2         None
3         None
4         None
          ...
368206    None
368207    None
368208    None
368209    None
368210    None
Length: 47235, dtype: object

In [146]:
print(empty_dict)

{('2018-12-20', '00:00:00'): 13328, ('2018-12-20', '00:15:00'): 13199, ('2018-12-20', '00:30:00'): 13069, ('2018-12-20', '00:45:00'): 12930, ('2018-12-20', '01:00:00'): 12790, ('2018-12-20', '01:15:00'): 12772, ('2018-12-20', '01:30:00'): 12753, ('2018-12-20', '01:45:00'): 12724, ('2018-12-20', '02:00:00'): 12955, ('2018-12-20', '02:15:00'): 12983, ('2018-12-20', '02:30:00'): 13007, ('2018-12-20', '02:45:00'): 13049, ('2018-12-20', '03:00:00'): 13091, ('2018-12-20', '03:15:00'): 13151, ('2018-12-20', '03:30:00'): 13207, ('2018-12-20', '03:45:00'): 13265, ('2018-12-20', '04:00:00'): 13322, ('2018-12-20', '04:15:00'): 13508, ('2018-12-20', '04:30:00'): 13698, ('2018-12-20', '04:45:00'): 13889, ('2018-12-20', '05:00:00'): 14081, ('2018-12-20', '05:15:00'): 14285, ('2018-12-20', '05:30:00'): 14492, ('2018-12-20', '05:45:00'): 14698, ('2018-12-20', '06:00:00'): 15067, ('2018-12-20', '06:15:00'): 15301, ('2018-12-20', '06:30:00'): 15536, ('2018-12-20', '06:45:00'): 15759, ('2018-12-20', '07:00:00'): 15979, ('2018-12-20', '07:15:00'): 16153, ('2018-12-20', '07:30:00'): 16328, ('2018-12-20', '07:45:00'): 16504, ('2018-12-20', '08:00:00'): 16687, ('2018-12-20', '08:15:00'): 16852, ('2018-12-20', '08:30:00'): 17019, ('2018-12-20', '08:45:00'): 17163, ('2018-12-20', '09:00:00'): 17308, ('2018-12-20', '09:15:00'): 17375, ('2018-12-20', '09:30:00'): 17439, ('2018-12-20', '09:45:00'): 17496, ('2018-12-20', '10:00:00'): 17551, ('2018-12-20', '10:15:00'): 17521, ('2018-12-20', '10:30:00'): 17489, ('2018-12-20', '10:45:00'): 17492, ('2018-12-20', '11:00:00'): 17497, ('2018-12-20', '11:15:00'): 17521, ('2018-12-20', '11:30:00'): 17549, ('2018-12-20', '11:45:00'): 17577, ('2018-12-20', '12:00:00'): 17604, ('2018-12-20', '12:15:00'): 17636, ('2018-12-20', '12:30:00'): 17667, ('2018-12-20', '12:45:00'): 17687, ('2018-12-20', '13:00:00'): 17708, ('2018-12-20', '13:15:00'): 17809, ('2018-12-20', '13:30:00'): 17909, ('2018-12-20', '13:45:00'): 17980, ('2018-12-20', '14:00:00'): 18053, ('2018-12-20', '14:15:00'): 18187, ('2018-12-20', '14:30:00'): 18315, ('2018-12-20', '14:45:00'): 18446, ('2018-12-20', '15:00:00'): 18578, ('2018-12-20', '15:15:00'): 18720, ('2018-12-20', '15:30:00'): 18859, ('2018-12-20', '15:45:00'): 19027, ('2018-12-20', '16:00:00'): 19207, ('2018-12-20', '16:15:00'): 19480, ('2018-12-20', '16:30:00'): 19757, ('2018-12-20', '16:45:00'): 20036, ('2018-12-20', '17:00:00'): 20315, ('2018-12-20', '17:15:00'): 20588, ('2018-12-20', '17:30:00'): 20860, ('2018-12-20', '17:45:00'): 21135, ('2018-12-20', '18:00:00'): 21408, ('2018-12-20', '18:15:00'): 21670, ('2018-12-20', '18:30:00'): 21666, ('2018-12-20', '18:45:00'): 21940, ('2018-12-20', '19:00:00'): 22213, ('2018-12-20', '19:15:00'): 22366, ('2018-12-20', '19:30:00'): 22521, ('2018-12-20', '19:45:00'): 22665, ('2018-12-20', '20:00:00'): 22807, ('2018-12-20', '20:15:00'): 22939, ('2018-12-20', '20:30:00'): 23069, ('2018-12-20', '20:45:00'): 23192, ('2018-12-20', '21:00:00'): 23311, ('2018-12-20', '21:15:00'): 23495, ('2018-12-20', '21:30:00'): 23680, ('2018-12-20', '21:45:00'): 23845, ('2018-12-20', '22:00:00'): 23516, ('2018-12-20', '22:15:00'): 23602, ('2018-12-20', '22:30:00'): 23686, ('2018-12-20', '22:45:00'): 23762, ('2018-12-20', '23:00:00'): 23836, ('2018-12-20', '23:15:00'): 23893, ('2018-12-20', '23:30:00'): 23930, ('2018-12-20', '23:45:00'): 24078, ('2018-12-21', '00:00:00'): 22967, ('2018-12-21', '00:15:00'): 23035, ('2018-12-21', '00:30:00'): 23100, ('2018-12-21', '00:45:00'): 23163, ('2018-12-21', '01:00:00'): 23225, ('2018-12-21', '01:15:00'): 23228, ('2018-12-21', '01:30:00'): 23233, ('2018-12-21', '01:45:00'): 23260, ('2018-12-21', '02:00:00'): 23382, ('2018-12-21', '02:15:00'): 23335, ('2018-12-21', '02:30:00'): 23281, ('2018-12-21', '02:45:00'): 23218, ('2018-12-21', '03:00:00'): 23155, ('2018-12-21', '03:15:00'): 23154, ('2018-12-21', '03:30:00'): 23155, ('2018-12-21', '03:45:00'): 23152, ('2018-12-21', '04:00:00'): 23152, ('2018-12-21', '04:15:00'): 23010, ('2018-12-21', '04:30:00'): 22872, ('2018-12-21', '04:45:00'): 22727, ('2018-12-21', '05:00:00'): 22583, ('2018-12-21', '05:15:00'): 22435, ('2018-12-21', '05:30:00'): 22270, ('2018-12-21', '05:45:00'): 22115, ('2018-12-21', '06:00:00'): 22423, ('2018-12-21', '06:15:00'): 22348, ('2018-12-21', '06:30:00'): 22267, ('2018-12-21', '06:45:00'): 22178, ('2018-12-21', '07:00:00'): 22092, ('2018-12-21', '07:15:00'): 22107, ('2018-12-21', '07:30:00'): 22121, ('2018-12-21', '07:45:00'): 22149, ('2018-12-21', '08:00:00'): 22172, ('2018-12-21', '08:15:00'): 22270, ('2018-12-21', '08:30:00'): 22360, ('2018-12-21', '08:45:00'): 22446, ('2018-12-21', '09:00:00'): 22528, ('2018-12-21', '09:15:00'): 22596, ('2018-12-21', '09:30:00'): 22666, ('2018-12-21', '09:45:00'): 22721, ('2018-12-21', '10:00:00'): 22766, ('2018-12-21', '10:15:00'): 22793, ('2018-12-21', '10:30:00'): 22817, ('2018-12-21', '10:45:00'): 22852, ('2018-12-21', '11:00:00'): 22886, ('2018-12-21', '11:15:00'): 22920, ('2018-12-21', '11:30:00'): 22944, ('2018-12-21', '11:45:00'): 22971, ('2018-12-21', '12:00:00'): 22996, ('2018-12-21', '12:15:00'): 23059, ('2018-12-21', '12:30:00'): 23120, ('2018-12-21', '12:45:00'): 23190, ('2018-12-21', '13:00:00'): 23263, ('2018-12-21', '13:15:00'): 23394, ('2018-12-21', '13:30:00'): 23524, ('2018-12-21', '13:45:00'): 23688, ('2018-12-21', '14:00:00'): 23856, ('2018-12-21', '14:15:00'): 24091, ('2018-12-21', '14:30:00'): 24323, ('2018-12-21', '14:45:00'): 24593, ('2018-12-21', '15:00:00'): 24883, ('2018-12-21', '15:15:00'): 25210, ('2018-12-21', '15:30:00'): 25527, ('2018-12-21', '15:45:00'): 25841, ('2018-12-21', '16:00:00'): 26163, ('2018-12-21', '16:15:00'): 26492, ('2018-12-21', '16:30:00'): 26814, ('2018-12-21', '16:45:00'): 27126, ('2018-12-21', '17:00:00'): 27452, ('2018-12-21', '17:15:00'): 27895, ('2018-12-21', '17:30:00'): 28339, ('2018-12-21', '17:45:00'): 28804, ('2018-12-21', '18:00:00'): 29287, ('2018-12-21', '18:15:00'): 29735, ('2018-12-21', '18:30:00'): 30175, ('2018-12-21', '18:45:00'): 30615, ('2018-12-21', '19:00:00'): 31036, ('2018-12-21', '19:15:00'): 31322, ('2018-12-21', '19:30:00'): 31598, ('2018-12-21', '19:45:00'): 31839, ('2018-12-21', '20:00:00'): 32094, ('2018-12-21', '20:15:00'): 32335, ('2018-12-21', '20:30:00'): 32580, ('2018-12-21', '20:45:00'): 32818, ('2018-12-21', '21:00:00'): 33051, ('2018-12-21', '21:15:00'): 33179, ('2018-12-21', '21:30:00'): 33302, ('2018-12-21', '21:45:00'): 33443, ('2018-12-21', '22:00:00'): 32662, ('2018-12-21', '22:15:00'): 32691, ('2018-12-21', '22:30:00'): 32711, ('2018-12-21', '22:45:00'): 32706, ('2018-12-21', '23:00:00'): 32702, ('2018-12-21', '23:15:00'): 32658, ('2018-12-21', '23:30:00'): 32595, ('2018-12-21', '23:45:00'): 32517, ('2018-12-22', '00:00:00'): 38441, ('2018-12-22', '00:15:00'): 38262, ('2018-12-22', '00:30:00'): 38067, ('2018-12-22', '00:45:00'): 37870, ('2018-12-22', '01:00:00'): 37668, ('2018-12-22', '01:15:00'): 37333, ('2018-12-22', '01:30:00'): 36989, ('2018-12-22', '01:45:00'): 36609, ('2018-12-22', '02:00:00'): 36207, ('2018-12-22', '02:15:00'): 35896, ('2018-12-22', '02:30:00'): 35437, ('2018-12-22', '02:45:00'): 34976, ('2018-12-22', '03:00:00'): 34520, ('2018-12-22', '03:15:00'): 34029, ('2018-12-22', '03:30:00'): 33546, ('2018-12-22', '03:45:00'): 33061, ('2018-12-22', '04:00:00'): 32592, ('2018-12-22', '04:15:00'): 32149, ('2018-12-22', '04:30:00'): 31691, ('2018-12-22', '04:45:00'): 31197, ('2018-12-22', '05:00:00'): 30677, ('2018-12-22', '05:15:00'): 30180, ('2018-12-22', '05:30:00'): 29664, ('2018-12-22', '05:45:00'): 29141, ('2018-12-22', '06:00:00'): 29196, ('2018-12-22', '06:15:00'): 28736, ('2018-12-22', '06:30:00'): 28280, ('2018-12-22', '06:45:00'): 27787, ('2018-12-22', '07:00:00'): 27285, ('2018-12-22', '07:15:00'): 26999, ('2018-12-22', '07:30:00'): 26703, ('2018-12-22', '07:45:00'): 26352, ('2018-12-22', '08:00:00'): 26002, ('2018-12-22', '08:15:00'): 25730, ('2018-12-22', '08:30:00'): 25454, ('2018-12-22', '08:45:00'): 25181, ('2018-12-22', '09:00:00'): 24904, ('2018-12-22', '09:15:00'): 24713, ('2018-12-22', '09:30:00'): 24521, ('2018-12-22', '09:45:00'): 24337, ('2018-12-22', '10:00:00'): 24155, ('2018-12-22', '10:15:00'): 24097, ('2018-12-22', '10:30:00'): 24039, ('2018-12-22', '10:45:00'): 24012, ('2018-12-22', '11:00:00'): 23982, ('2018-12-22', '11:15:00'): 23916, ('2018-12-22', '11:30:00'): 23852, ('2018-12-22', '11:45:00'): 23801, ('2018-12-22', '12:00:00'): 23756, ('2018-12-22', '12:15:00'): 23710, ('2018-12-22', '12:30:00'): 23661, ('2018-12-22', '12:45:00'): 23643, ('2018-12-22', '13:00:00'): 23620, ('2018-12-22', '13:15:00'): 23408, ('2018-12-22', '13:30:00'): 23201, ('2018-12-22', '13:45:00'): 22934, ('2018-12-22', '14:00:00'): 22668, ('2018-12-22', '14:15:00'): 22379, ('2018-12-22', '14:30:00'): 22090, ('2018-12-22', '14:45:00'): 21801, ('2018-12-22', '15:00:00'): 21500, ('2018-12-22', '15:15:00'): 21254, ('2018-12-22', '15:30:00'): 21001, ('2018-12-22', '15:45:00'): 20748, ('2018-12-22', '16:00:00'): 20502, ('2018-12-22', '16:15:00'): 20360, ('2018-12-22', '16:30:00'): 20219, ('2018-12-22', '16:45:00'): 20096, ('2018-12-22', '17:00:00'): 19969, ('2018-12-22', '17:15:00'): 19918, ('2018-12-22', '17:30:00'): 19866, ('2018-12-22', '17:45:00'): 19833, ('2018-12-22', '18:00:00'): 19807, ('2018-12-22', '18:15:00'): 19716, ('2018-12-22', '18:30:00'): 19624, ('2018-12-22', '18:45:00'): 19528, ('2018-12-22', '19:00:00'): 19433, ('2018-12-22', '19:15:00'): 19487, ('2018-12-22', '19:30:00'): 19540, ('2018-12-22', '19:45:00'): 19579, ('2018-12-22', '20:00:00'): 19618, ('2018-12-22', '20:15:00'): 19722, ('2018-12-22', '20:30:00'): 19830, ('2018-12-22', '20:45:00'): 19923, ('2018-12-22', '21:00:00'): 20016, ('2018-12-22', '21:15:00'): 20173, ('2018-12-22', '21:30:00'): 20331, ('2018-12-22', '21:45:00'): 20466, ('2018-12-22', '22:00:00'): 20217, ('2018-12-22', '22:15:00'): 20317, ('2018-12-22', '22:30:00'): 20284, ('2018-12-22', '22:45:00'): 20401, ('2018-12-22', '23:00:00'): 20506, ('2018-12-22', '23:15:00'): 20608, ('2018-12-22', '23:30:00'): 20711, ('2018-12-22', '23:45:00'): 20828, ('2018-12-23', '00:00:00'): 20737, ('2018-12-23', '00:15:00'): 20767, ('2018-12-23', '00:30:00'): 20799, ('2018-12-23', '00:45:00'): 20839, ('2018-12-23', '01:00:00'): 20701, ('2018-12-23', '01:15:00'): 20713, ('2018-12-23', '01:30:00'): 20720, ('2018-12-23', '01:45:00'): 20743, ('2018-12-23', '02:00:00'): 20853, ('2018-12-23', '02:15:00'): 20909, ('2018-12-23', '02:30:00'): 20957, ('2018-12-23', '02:45:00'): 21002, ('2018-12-23', '03:00:00'): 21044, ('2018-12-23', '03:15:00'): 21115, ('2018-12-23', '03:30:00'): 21186, ('2018-12-23', '03:45:00'): 21293, ('2018-12-23', '04:00:00'): 21401, ('2018-12-23', '04:15:00'): 21505, ('2018-12-23', '04:30:00'): 21607, ('2018-12-23', '04:45:00'): 21690, ('2018-12-23', '05:00:00'): 21763, ('2018-12-23', '05:15:00'): 21838, ('2018-12-23', '05:30:00'): 21908, ('2018-12-23', '05:45:00'): 21990, ('2018-12-23', '06:00:00'): 22496, ('2018-12-23', '06:15:00'): 22561, ('2018-12-23', '06:30:00'): 22621, ('2018-12-23', '06:45:00'): 22677, ('2018-12-23', '07:00:00'): 22869, ('2018-12-23', '07:15:00'): 22933, ('2018-12-23', '07:30:00'): 22998, ('2018-12-23', '07:45:00'): 23066, ('2018-12-23', '08:00:00'): 23127, ('2018-12-23', '08:15:00'): 23221, ('2018-12-23', '08:30:00'): 23314, ('2018-12-23', '08:45:00'): 23394, ('2018-12-23', '09:00:00'): 23478, ('2018-12-23', '09:15:00'): 23518, ('2018-12-23', '09:30:00'): 23554, ('2018-12-23', '09:45:00'): 23575, ('2018-12-23', '10:00:00'): 23601, ('2018-12-23', '10:15:00'): 23471, ('2018-12-23', '10:30:00'): 23337, ('2018-12-23', '10:45:00'): 23213, ('2018-12-23', '11:00:00'): 23093, ('2018-12-23', '11:15:00'): 22945, ('2018-12-23', '11:30:00'): 22790, ('2018-12-23', '11:45:00'): 22650, ('2018-12-23', '12:00:00'): 22511, ('2018-12-23', '12:15:00'): 22255, ('2018-12-23', '12:30:00'): 22007, ('2018-12-23', '12:45:00'): 21742, ('2018-12-23', '13:00:00'): 21473, ('2018-12-23', '13:15:00'): 20808, ('2018-12-23', '13:30:00'): 20130, ('2018-12-23', '13:45:00'): 19443, ('2018-12-23', '14:00:00'): 18766, ('2018-12-23', '14:15:00'): 18187, ('2018-12-23', '14:30:00'): 17601, ('2018-12-23', '14:45:00'): 17026, ('2018-12-23', '15:00:00'): 16444, ('2018-12-23', '15:15:00'): 15877, ('2018-12-23', '15:30:00'): 15325, ('2018-12-23', '15:45:00'): 14788, ('2018-12-23', '16:00:00'): 14244, ('2018-12-23', '16:15:00'): 13796, ('2018-12-23', '16:30:00'): 13344, ('2018-12-23', '16:45:00'): 12883, ('2018-12-23', '17:00:00'): 12415, ('2018-12-23', '17:15:00'): 12063, ('2018-12-23', '17:30:00'): 11704, ('2018-12-23', '17:45:00'): 11331, ('2018-12-23', '18:00:00'): 10955, ('2018-12-23', '18:15:00'): 10637, ('2018-12-23', '18:30:00'): 10316, ('2018-12-23', '18:45:00'): 10013, ('2018-12-23', '19:00:00'): 9705, ('2018-12-23', '19:15:00'): 9544, ('2018-12-23', '19:30:00'): 9387, ('2018-12-23', '19:45:00'): 9233, ('2018-12-23', '20:00:00'): 9075, ('2018-12-23', '20:15:00'): 8938, ('2018-12-23', '20:30:00'): 8801, ('2018-12-23', '20:45:00'): 8665, ('2018-12-23', '21:00:00'): 8525, ('2018-12-23', '21:15:00'): 8417, ('2018-12-23', '21:30:00'): 8316, ('2018-12-23', '21:45:00'): 8226, ('2018-12-23', '22:00:00'): 8074, ('2018-12-23', '22:15:00'): 8047, ('2018-12-23', '22:30:00'): 8014, ('2018-12-23', '22:45:00'): 7974, ('2018-12-23', '23:00:00'): 7933, ('2018-12-23', '23:15:00'): 7919, ('2018-12-23', '23:30:00'): 7914, ('2018-12-23', '23:45:00'): 7937, ('2018-12-24', '00:00:00'): 12102, ('2018-12-24', '00:15:00'): 12279, ('2018-12-24', '00:30:00'): 12467, ('2018-12-24', '00:45:00'): 12641, ('2018-12-24', '01:00:00'): 12818, ('2018-12-24', '01:15:00'): 12848, ('2018-12-24', '01:30:00'): 12875, ('2018-12-24', '01:45:00'): 12903, ('2018-12-24', '02:00:00'): 13154, ('2018-12-24', '02:15:00'): 13241, ('2018-12-24', '02:30:00'): 13325, ('2018-12-24', '02:45:00'): 13397, ('2018-12-24', '03:00:00'): 13462, ('2018-12-24', '03:15:00'): 13605, ('2018-12-24', '03:30:00'): 13752, ('2018-12-24', '03:45:00'): 13897, ('2018-12-24', '04:00:00'): 14034, ('2018-12-24', '04:15:00'): 14040, ('2018-12-24', '04:30:00'): 14049, ('2018-12-24', '04:45:00'): 14051, ('2018-12-24', '05:00:00'): 14058, ('2018-12-24', '05:15:00'): 13963, ('2018-12-24', '05:30:00'): 13866, ('2018-12-24', '05:45:00'): 13745, ('2018-12-24', '06:00:00'): 13765, ('2018-12-24', '06:15:00'): 13596, ('2018-12-24', '06:30:00'): 13425, ('2018-12-24', '06:45:00'): 13260, ('2018-12-24', '07:00:00'): 13100, ('2018-12-24', '07:15:00'): 12863, ('2018-12-24', '07:30:00'): 12619, ('2018-12-24', '07:45:00'): 12364, ('2018-12-24', '08:00:00'): 12104, ('2018-12-24', '08:15:00'): 11823, ('2018-12-24', '08:30:00'): 11545, ('2018-12-24', '08:45:00'): 11288, ('2018-12-24', '09:00:00'): 11028, ('2018-12-24', '09:15:00'): 10828, ('2018-12-24', '09:30:00'): 10616, ('2018-12-24', '09:45:00'): 10400, ('2018-12-24', '10:00:00'): 10182, ('2018-12-24', '10:15:00'): 10173, ('2018-12-24', '10:30:00'): 10166, ('2018-12-24', '10:45:00'): 10168, ('2018-12-24', '11:00:00'): 10173, ('2018-12-24', '11:15:00'): 10242, ('2018-12-24', '11:30:00'): 10313, ('2018-12-24', '11:45:00'): 10384, ('2018-12-24', '12:00:00'): 10451, ('2018-12-24', '12:15:00'): 10532, ('2018-12-24', '12:30:00'): 10611, ('2018-12-24', '12:45:00'): 10700, ('2018-12-24', '13:00:00'): 10788, ('2018-12-24', '13:15:00'): 10803, ('2018-12-24', '13:30:00'): 10822, ('2018-12-24', '13:45:00'): 10839, ('2018-12-24', '14:00:00'): 10851, ('2018-12-24', '14:15:00'): 10846, ('2018-12-24', '14:30:00'): 10839, ('2018-12-24', '14:45:00'): 10827, ('2018-12-24', '15:00:00'): 10816, ('2018-12-24', '15:15:00'): 10893, ('2018-12-24', '15:30:00'): 10958, ('2018-12-24', '15:45:00'): 11024, ('2018-12-24', '16:00:00'): 11087, ('2018-12-24', '16:15:00'): 11291, ('2018-12-24', '16:30:00'): 11507, ('2018-12-24', '16:45:00'): 11739, ('2018-12-24', '17:00:00'): 11932, ('2018-12-24', '17:15:00'): 12175, ('2018-12-24', '17:30:00'): 12420, ('2018-12-24', '17:45:00'): 12674, ('2018-12-24', '18:00:00'): 12931, ('2018-12-24', '18:15:00'): 13173, ('2018-12-24', '18:30:00'): 13422, ('2018-12-24', '18:45:00'): 13677, ('2018-12-24', '19:00:00'): 13929, ('2018-12-24', '19:15:00'): 14145, ('2018-12-24', '19:30:00'): 14359, ('2018-12-24', '19:45:00'): 14548, ('2018-12-24', '20:00:00'): 14740, ('2018-12-24', '20:15:00'): 14971, ('2018-12-24', '20:30:00'): 15199, ('2018-12-24', '20:45:00'): 15423, ('2018-12-24', '21:00:00'): 15644, ('2018-12-24', '21:15:00'): 15885, ('2018-12-24', '21:30:00'): 16124, ('2018-12-24', '21:45:00'): 16369, ('2018-12-24', '22:00:00'): 16424, ('2018-12-24', '22:15:00'): 16615, ('2018-12-24', '22:30:00'): 16798, ('2018-12-24', '22:45:00'): 16967, ('2018-12-24', '23:00:00'): 17138, ('2018-12-24', '23:15:00'): 17300, ('2018-12-24', '23:30:00'): 17466, ('2018-12-24', '23:45:00'): 17634, ('2018-12-25', '00:00:00'): 18459}

In [26]:
subtracted_date = df['delivery_start'].dt.date- timedelta(1)
subtracted_date = subtracted_date.strftime("%Y-%m-%d")
print(subtracted_date)

AttributeError: 'Series' object has no attribute 'strftime'

In [147]:
def cal(x,y,z):   
            final_val = z - empty_dict[str(x.date()),str(x.time())] 
            return int(final_val)

In [408]:
data = df['delivery_start',].apply(cal,args=())

KeyError: ('delivery_start',)

In [148]:
%%time
df["ID Position"] = df.apply(lambda x: cal(x['delivery_start'], x['timestamp'], x['wind forecast in MW']), axis=1)

CPU times: user 497 ms, sys: 7.96 ms, total: 505 ms
Wall time: 503 ms

In [150]:
print(empty_dict)

{('2018-12-20', '00:00:00'): 13328, ('2018-12-20', '00:15:00'): 13199, ('2018-12-20', '00:30:00'): 13069, ('2018-12-20', '00:45:00'): 12930, ('2018-12-20', '01:00:00'): 12790, ('2018-12-20', '01:15:00'): 12772, ('2018-12-20', '01:30:00'): 12753, ('2018-12-20', '01:45:00'): 12724, ('2018-12-20', '02:00:00'): 12955, ('2018-12-20', '02:15:00'): 12983, ('2018-12-20', '02:30:00'): 13007, ('2018-12-20', '02:45:00'): 13049, ('2018-12-20', '03:00:00'): 13091, ('2018-12-20', '03:15:00'): 13151, ('2018-12-20', '03:30:00'): 13207, ('2018-12-20', '03:45:00'): 13265, ('2018-12-20', '04:00:00'): 13322, ('2018-12-20', '04:15:00'): 13508, ('2018-12-20', '04:30:00'): 13698, ('2018-12-20', '04:45:00'): 13889, ('2018-12-20', '05:00:00'): 14081, ('2018-12-20', '05:15:00'): 14285, ('2018-12-20', '05:30:00'): 14492, ('2018-12-20', '05:45:00'): 14698, ('2018-12-20', '06:00:00'): 15067, ('2018-12-20', '06:15:00'): 15301, ('2018-12-20', '06:30:00'): 15536, ('2018-12-20', '06:45:00'): 15759, ('2018-12-20', '07:00:00'): 15979, ('2018-12-20', '07:15:00'): 16153, ('2018-12-20', '07:30:00'): 16328, ('2018-12-20', '07:45:00'): 16504, ('2018-12-20', '08:00:00'): 16687, ('2018-12-20', '08:15:00'): 16852, ('2018-12-20', '08:30:00'): 17019, ('2018-12-20', '08:45:00'): 17163, ('2018-12-20', '09:00:00'): 17308, ('2018-12-20', '09:15:00'): 17375, ('2018-12-20', '09:30:00'): 17439, ('2018-12-20', '09:45:00'): 17496, ('2018-12-20', '10:00:00'): 17551, ('2018-12-20', '10:15:00'): 17521, ('2018-12-20', '10:30:00'): 17489, ('2018-12-20', '10:45:00'): 17492, ('2018-12-20', '11:00:00'): 17497, ('2018-12-20', '11:15:00'): 17521, ('2018-12-20', '11:30:00'): 17549, ('2018-12-20', '11:45:00'): 17577, ('2018-12-20', '12:00:00'): 17604, ('2018-12-20', '12:15:00'): 17636, ('2018-12-20', '12:30:00'): 17667, ('2018-12-20', '12:45:00'): 17687, ('2018-12-20', '13:00:00'): 17708, ('2018-12-20', '13:15:00'): 17809, ('2018-12-20', '13:30:00'): 17909, ('2018-12-20', '13:45:00'): 17980, ('2018-12-20', '14:00:00'): 18053, ('2018-12-20', '14:15:00'): 18187, ('2018-12-20', '14:30:00'): 18315, ('2018-12-20', '14:45:00'): 18446, ('2018-12-20', '15:00:00'): 18578, ('2018-12-20', '15:15:00'): 18720, ('2018-12-20', '15:30:00'): 18859, ('2018-12-20', '15:45:00'): 19027, ('2018-12-20', '16:00:00'): 19207, ('2018-12-20', '16:15:00'): 19480, ('2018-12-20', '16:30:00'): 19757, ('2018-12-20', '16:45:00'): 20036, ('2018-12-20', '17:00:00'): 20315, ('2018-12-20', '17:15:00'): 20588, ('2018-12-20', '17:30:00'): 20860, ('2018-12-20', '17:45:00'): 21135, ('2018-12-20', '18:00:00'): 21408, ('2018-12-20', '18:15:00'): 21670, ('2018-12-20', '18:30:00'): 21666, ('2018-12-20', '18:45:00'): 21940, ('2018-12-20', '19:00:00'): 22213, ('2018-12-20', '19:15:00'): 22366, ('2018-12-20', '19:30:00'): 22521, ('2018-12-20', '19:45:00'): 22665, ('2018-12-20', '20:00:00'): 22807, ('2018-12-20', '20:15:00'): 22939, ('2018-12-20', '20:30:00'): 23069, ('2018-12-20', '20:45:00'): 23192, ('2018-12-20', '21:00:00'): 23311, ('2018-12-20', '21:15:00'): 23495, ('2018-12-20', '21:30:00'): 23680, ('2018-12-20', '21:45:00'): 23845, ('2018-12-20', '22:00:00'): 23516, ('2018-12-20', '22:15:00'): 23602, ('2018-12-20', '22:30:00'): 23686, ('2018-12-20', '22:45:00'): 23762, ('2018-12-20', '23:00:00'): 23836, ('2018-12-20', '23:15:00'): 23893, ('2018-12-20', '23:30:00'): 23930, ('2018-12-20', '23:45:00'): 24078, ('2018-12-21', '00:00:00'): 22967, ('2018-12-21', '00:15:00'): 23035, ('2018-12-21', '00:30:00'): 23100, ('2018-12-21', '00:45:00'): 23163, ('2018-12-21', '01:00:00'): 23225, ('2018-12-21', '01:15:00'): 23228, ('2018-12-21', '01:30:00'): 23233, ('2018-12-21', '01:45:00'): 23260, ('2018-12-21', '02:00:00'): 23382, ('2018-12-21', '02:15:00'): 23335, ('2018-12-21', '02:30:00'): 23281, ('2018-12-21', '02:45:00'): 23218, ('2018-12-21', '03:00:00'): 23155, ('2018-12-21', '03:15:00'): 23154, ('2018-12-21', '03:30:00'): 23155, ('2018-12-21', '03:45:00'): 23152, ('2018-12-21', '04:00:00'): 23152, ('2018-12-21', '04:15:00'): 23010, ('2018-12-21', '04:30:00'): 22872, ('2018-12-21', '04:45:00'): 22727, ('2018-12-21', '05:00:00'): 22583, ('2018-12-21', '05:15:00'): 22435, ('2018-12-21', '05:30:00'): 22270, ('2018-12-21', '05:45:00'): 22115, ('2018-12-21', '06:00:00'): 22423, ('2018-12-21', '06:15:00'): 22348, ('2018-12-21', '06:30:00'): 22267, ('2018-12-21', '06:45:00'): 22178, ('2018-12-21', '07:00:00'): 22092, ('2018-12-21', '07:15:00'): 22107, ('2018-12-21', '07:30:00'): 22121, ('2018-12-21', '07:45:00'): 22149, ('2018-12-21', '08:00:00'): 22172, ('2018-12-21', '08:15:00'): 22270, ('2018-12-21', '08:30:00'): 22360, ('2018-12-21', '08:45:00'): 22446, ('2018-12-21', '09:00:00'): 22528, ('2018-12-21', '09:15:00'): 22596, ('2018-12-21', '09:30:00'): 22666, ('2018-12-21', '09:45:00'): 22721, ('2018-12-21', '10:00:00'): 22766, ('2018-12-21', '10:15:00'): 22793, ('2018-12-21', '10:30:00'): 22817, ('2018-12-21', '10:45:00'): 22852, ('2018-12-21', '11:00:00'): 22886, ('2018-12-21', '11:15:00'): 22920, ('2018-12-21', '11:30:00'): 22944, ('2018-12-21', '11:45:00'): 22971, ('2018-12-21', '12:00:00'): 22996, ('2018-12-21', '12:15:00'): 23059, ('2018-12-21', '12:30:00'): 23120, ('2018-12-21', '12:45:00'): 23190, ('2018-12-21', '13:00:00'): 23263, ('2018-12-21', '13:15:00'): 23394, ('2018-12-21', '13:30:00'): 23524, ('2018-12-21', '13:45:00'): 23688, ('2018-12-21', '14:00:00'): 23856, ('2018-12-21', '14:15:00'): 24091, ('2018-12-21', '14:30:00'): 24323, ('2018-12-21', '14:45:00'): 24593, ('2018-12-21', '15:00:00'): 24883, ('2018-12-21', '15:15:00'): 25210, ('2018-12-21', '15:30:00'): 25527, ('2018-12-21', '15:45:00'): 25841, ('2018-12-21', '16:00:00'): 26163, ('2018-12-21', '16:15:00'): 26492, ('2018-12-21', '16:30:00'): 26814, ('2018-12-21', '16:45:00'): 27126, ('2018-12-21', '17:00:00'): 27452, ('2018-12-21', '17:15:00'): 27895, ('2018-12-21', '17:30:00'): 28339, ('2018-12-21', '17:45:00'): 28804, ('2018-12-21', '18:00:00'): 29287, ('2018-12-21', '18:15:00'): 29735, ('2018-12-21', '18:30:00'): 30175, ('2018-12-21', '18:45:00'): 30615, ('2018-12-21', '19:00:00'): 31036, ('2018-12-21', '19:15:00'): 31322, ('2018-12-21', '19:30:00'): 31598, ('2018-12-21', '19:45:00'): 31839, ('2018-12-21', '20:00:00'): 32094, ('2018-12-21', '20:15:00'): 32335, ('2018-12-21', '20:30:00'): 32580, ('2018-12-21', '20:45:00'): 32818, ('2018-12-21', '21:00:00'): 33051, ('2018-12-21', '21:15:00'): 33179, ('2018-12-21', '21:30:00'): 33302, ('2018-12-21', '21:45:00'): 33443, ('2018-12-21', '22:00:00'): 32662, ('2018-12-21', '22:15:00'): 32691, ('2018-12-21', '22:30:00'): 32711, ('2018-12-21', '22:45:00'): 32706, ('2018-12-21', '23:00:00'): 32702, ('2018-12-21', '23:15:00'): 32658, ('2018-12-21', '23:30:00'): 32595, ('2018-12-21', '23:45:00'): 32517, ('2018-12-22', '00:00:00'): 38441, ('2018-12-22', '00:15:00'): 38262, ('2018-12-22', '00:30:00'): 38067, ('2018-12-22', '00:45:00'): 37870, ('2018-12-22', '01:00:00'): 37668, ('2018-12-22', '01:15:00'): 37333, ('2018-12-22', '01:30:00'): 36989, ('2018-12-22', '01:45:00'): 36609, ('2018-12-22', '02:00:00'): 36207, ('2018-12-22', '02:15:00'): 35896, ('2018-12-22', '02:30:00'): 35437, ('2018-12-22', '02:45:00'): 34976, ('2018-12-22', '03:00:00'): 34520, ('2018-12-22', '03:15:00'): 34029, ('2018-12-22', '03:30:00'): 33546, ('2018-12-22', '03:45:00'): 33061, ('2018-12-22', '04:00:00'): 32592, ('2018-12-22', '04:15:00'): 32149, ('2018-12-22', '04:30:00'): 31691, ('2018-12-22', '04:45:00'): 31197, ('2018-12-22', '05:00:00'): 30677, ('2018-12-22', '05:15:00'): 30180, ('2018-12-22', '05:30:00'): 29664, ('2018-12-22', '05:45:00'): 29141, ('2018-12-22', '06:00:00'): 29196, ('2018-12-22', '06:15:00'): 28736, ('2018-12-22', '06:30:00'): 28280, ('2018-12-22', '06:45:00'): 27787, ('2018-12-22', '07:00:00'): 27285, ('2018-12-22', '07:15:00'): 26999, ('2018-12-22', '07:30:00'): 26703, ('2018-12-22', '07:45:00'): 26352, ('2018-12-22', '08:00:00'): 26002, ('2018-12-22', '08:15:00'): 25730, ('2018-12-22', '08:30:00'): 25454, ('2018-12-22', '08:45:00'): 25181, ('2018-12-22', '09:00:00'): 24904, ('2018-12-22', '09:15:00'): 24713, ('2018-12-22', '09:30:00'): 24521, ('2018-12-22', '09:45:00'): 24337, ('2018-12-22', '10:00:00'): 24155, ('2018-12-22', '10:15:00'): 24097, ('2018-12-22', '10:30:00'): 24039, ('2018-12-22', '10:45:00'): 24012, ('2018-12-22', '11:00:00'): 23982, ('2018-12-22', '11:15:00'): 23916, ('2018-12-22', '11:30:00'): 23852, ('2018-12-22', '11:45:00'): 23801, ('2018-12-22', '12:00:00'): 23756, ('2018-12-22', '12:15:00'): 23710, ('2018-12-22', '12:30:00'): 23661, ('2018-12-22', '12:45:00'): 23643, ('2018-12-22', '13:00:00'): 23620, ('2018-12-22', '13:15:00'): 23408, ('2018-12-22', '13:30:00'): 23201, ('2018-12-22', '13:45:00'): 22934, ('2018-12-22', '14:00:00'): 22668, ('2018-12-22', '14:15:00'): 22379, ('2018-12-22', '14:30:00'): 22090, ('2018-12-22', '14:45:00'): 21801, ('2018-12-22', '15:00:00'): 21500, ('2018-12-22', '15:15:00'): 21254, ('2018-12-22', '15:30:00'): 21001, ('2018-12-22', '15:45:00'): 20748, ('2018-12-22', '16:00:00'): 20502, ('2018-12-22', '16:15:00'): 20360, ('2018-12-22', '16:30:00'): 20219, ('2018-12-22', '16:45:00'): 20096, ('2018-12-22', '17:00:00'): 19969, ('2018-12-22', '17:15:00'): 19918, ('2018-12-22', '17:30:00'): 19866, ('2018-12-22', '17:45:00'): 19833, ('2018-12-22', '18:00:00'): 19807, ('2018-12-22', '18:15:00'): 19716, ('2018-12-22', '18:30:00'): 19624, ('2018-12-22', '18:45:00'): 19528, ('2018-12-22', '19:00:00'): 19433, ('2018-12-22', '19:15:00'): 19487, ('2018-12-22', '19:30:00'): 19540, ('2018-12-22', '19:45:00'): 19579, ('2018-12-22', '20:00:00'): 19618, ('2018-12-22', '20:15:00'): 19722, ('2018-12-22', '20:30:00'): 19830, ('2018-12-22', '20:45:00'): 19923, ('2018-12-22', '21:00:00'): 20016, ('2018-12-22', '21:15:00'): 20173, ('2018-12-22', '21:30:00'): 20331, ('2018-12-22', '21:45:00'): 20466, ('2018-12-22', '22:00:00'): 20217, ('2018-12-22', '22:15:00'): 20317, ('2018-12-22', '22:30:00'): 20284, ('2018-12-22', '22:45:00'): 20401, ('2018-12-22', '23:00:00'): 20506, ('2018-12-22', '23:15:00'): 20608, ('2018-12-22', '23:30:00'): 20711, ('2018-12-22', '23:45:00'): 20828, ('2018-12-23', '00:00:00'): 20737, ('2018-12-23', '00:15:00'): 20767, ('2018-12-23', '00:30:00'): 20799, ('2018-12-23', '00:45:00'): 20839, ('2018-12-23', '01:00:00'): 20701, ('2018-12-23', '01:15:00'): 20713, ('2018-12-23', '01:30:00'): 20720, ('2018-12-23', '01:45:00'): 20743, ('2018-12-23', '02:00:00'): 20853, ('2018-12-23', '02:15:00'): 20909, ('2018-12-23', '02:30:00'): 20957, ('2018-12-23', '02:45:00'): 21002, ('2018-12-23', '03:00:00'): 21044, ('2018-12-23', '03:15:00'): 21115, ('2018-12-23', '03:30:00'): 21186, ('2018-12-23', '03:45:00'): 21293, ('2018-12-23', '04:00:00'): 21401, ('2018-12-23', '04:15:00'): 21505, ('2018-12-23', '04:30:00'): 21607, ('2018-12-23', '04:45:00'): 21690, ('2018-12-23', '05:00:00'): 21763, ('2018-12-23', '05:15:00'): 21838, ('2018-12-23', '05:30:00'): 21908, ('2018-12-23', '05:45:00'): 21990, ('2018-12-23', '06:00:00'): 22496, ('2018-12-23', '06:15:00'): 22561, ('2018-12-23', '06:30:00'): 22621, ('2018-12-23', '06:45:00'): 22677, ('2018-12-23', '07:00:00'): 22869, ('2018-12-23', '07:15:00'): 22933, ('2018-12-23', '07:30:00'): 22998, ('2018-12-23', '07:45:00'): 23066, ('2018-12-23', '08:00:00'): 23127, ('2018-12-23', '08:15:00'): 23221, ('2018-12-23', '08:30:00'): 23314, ('2018-12-23', '08:45:00'): 23394, ('2018-12-23', '09:00:00'): 23478, ('2018-12-23', '09:15:00'): 23518, ('2018-12-23', '09:30:00'): 23554, ('2018-12-23', '09:45:00'): 23575, ('2018-12-23', '10:00:00'): 23601, ('2018-12-23', '10:15:00'): 23471, ('2018-12-23', '10:30:00'): 23337, ('2018-12-23', '10:45:00'): 23213, ('2018-12-23', '11:00:00'): 23093, ('2018-12-23', '11:15:00'): 22945, ('2018-12-23', '11:30:00'): 22790, ('2018-12-23', '11:45:00'): 22650, ('2018-12-23', '12:00:00'): 22511, ('2018-12-23', '12:15:00'): 22255, ('2018-12-23', '12:30:00'): 22007, ('2018-12-23', '12:45:00'): 21742, ('2018-12-23', '13:00:00'): 21473, ('2018-12-23', '13:15:00'): 20808, ('2018-12-23', '13:30:00'): 20130, ('2018-12-23', '13:45:00'): 19443, ('2018-12-23', '14:00:00'): 18766, ('2018-12-23', '14:15:00'): 18187, ('2018-12-23', '14:30:00'): 17601, ('2018-12-23', '14:45:00'): 17026, ('2018-12-23', '15:00:00'): 16444, ('2018-12-23', '15:15:00'): 15877, ('2018-12-23', '15:30:00'): 15325, ('2018-12-23', '15:45:00'): 14788, ('2018-12-23', '16:00:00'): 14244, ('2018-12-23', '16:15:00'): 13796, ('2018-12-23', '16:30:00'): 13344, ('2018-12-23', '16:45:00'): 12883, ('2018-12-23', '17:00:00'): 12415, ('2018-12-23', '17:15:00'): 12063, ('2018-12-23', '17:30:00'): 11704, ('2018-12-23', '17:45:00'): 11331, ('2018-12-23', '18:00:00'): 10955, ('2018-12-23', '18:15:00'): 10637, ('2018-12-23', '18:30:00'): 10316, ('2018-12-23', '18:45:00'): 10013, ('2018-12-23', '19:00:00'): 9705, ('2018-12-23', '19:15:00'): 9544, ('2018-12-23', '19:30:00'): 9387, ('2018-12-23', '19:45:00'): 9233, ('2018-12-23', '20:00:00'): 9075, ('2018-12-23', '20:15:00'): 8938, ('2018-12-23', '20:30:00'): 8801, ('2018-12-23', '20:45:00'): 8665, ('2018-12-23', '21:00:00'): 8525, ('2018-12-23', '21:15:00'): 8417, ('2018-12-23', '21:30:00'): 8316, ('2018-12-23', '21:45:00'): 8226, ('2018-12-23', '22:00:00'): 8074, ('2018-12-23', '22:15:00'): 8047, ('2018-12-23', '22:30:00'): 8014, ('2018-12-23', '22:45:00'): 7974, ('2018-12-23', '23:00:00'): 7933, ('2018-12-23', '23:15:00'): 7919, ('2018-12-23', '23:30:00'): 7914, ('2018-12-23', '23:45:00'): 7937, ('2018-12-24', '00:00:00'): 12102, ('2018-12-24', '00:15:00'): 12279, ('2018-12-24', '00:30:00'): 12467, ('2018-12-24', '00:45:00'): 12641, ('2018-12-24', '01:00:00'): 12818, ('2018-12-24', '01:15:00'): 12848, ('2018-12-24', '01:30:00'): 12875, ('2018-12-24', '01:45:00'): 12903, ('2018-12-24', '02:00:00'): 13154, ('2018-12-24', '02:15:00'): 13241, ('2018-12-24', '02:30:00'): 13325, ('2018-12-24', '02:45:00'): 13397, ('2018-12-24', '03:00:00'): 13462, ('2018-12-24', '03:15:00'): 13605, ('2018-12-24', '03:30:00'): 13752, ('2018-12-24', '03:45:00'): 13897, ('2018-12-24', '04:00:00'): 14034, ('2018-12-24', '04:15:00'): 14040, ('2018-12-24', '04:30:00'): 14049, ('2018-12-24', '04:45:00'): 14051, ('2018-12-24', '05:00:00'): 14058, ('2018-12-24', '05:15:00'): 13963, ('2018-12-24', '05:30:00'): 13866, ('2018-12-24', '05:45:00'): 13745, ('2018-12-24', '06:00:00'): 13765, ('2018-12-24', '06:15:00'): 13596, ('2018-12-24', '06:30:00'): 13425, ('2018-12-24', '06:45:00'): 13260, ('2018-12-24', '07:00:00'): 13100, ('2018-12-24', '07:15:00'): 12863, ('2018-12-24', '07:30:00'): 12619, ('2018-12-24', '07:45:00'): 12364, ('2018-12-24', '08:00:00'): 12104, ('2018-12-24', '08:15:00'): 11823, ('2018-12-24', '08:30:00'): 11545, ('2018-12-24', '08:45:00'): 11288, ('2018-12-24', '09:00:00'): 11028, ('2018-12-24', '09:15:00'): 10828, ('2018-12-24', '09:30:00'): 10616, ('2018-12-24', '09:45:00'): 10400, ('2018-12-24', '10:00:00'): 10182, ('2018-12-24', '10:15:00'): 10173, ('2018-12-24', '10:30:00'): 10166, ('2018-12-24', '10:45:00'): 10168, ('2018-12-24', '11:00:00'): 10173, ('2018-12-24', '11:15:00'): 10242, ('2018-12-24', '11:30:00'): 10313, ('2018-12-24', '11:45:00'): 10384, ('2018-12-24', '12:00:00'): 10451, ('2018-12-24', '12:15:00'): 10532, ('2018-12-24', '12:30:00'): 10611, ('2018-12-24', '12:45:00'): 10700, ('2018-12-24', '13:00:00'): 10788, ('2018-12-24', '13:15:00'): 10803, ('2018-12-24', '13:30:00'): 10822, ('2018-12-24', '13:45:00'): 10839, ('2018-12-24', '14:00:00'): 10851, ('2018-12-24', '14:15:00'): 10846, ('2018-12-24', '14:30:00'): 10839, ('2018-12-24', '14:45:00'): 10827, ('2018-12-24', '15:00:00'): 10816, ('2018-12-24', '15:15:00'): 10893, ('2018-12-24', '15:30:00'): 10958, ('2018-12-24', '15:45:00'): 11024, ('2018-12-24', '16:00:00'): 11087, ('2018-12-24', '16:15:00'): 11291, ('2018-12-24', '16:30:00'): 11507, ('2018-12-24', '16:45:00'): 11739, ('2018-12-24', '17:00:00'): 11932, ('2018-12-24', '17:15:00'): 12175, ('2018-12-24', '17:30:00'): 12420, ('2018-12-24', '17:45:00'): 12674, ('2018-12-24', '18:00:00'): 12931, ('2018-12-24', '18:15:00'): 13173, ('2018-12-24', '18:30:00'): 13422, ('2018-12-24', '18:45:00'): 13677, ('2018-12-24', '19:00:00'): 13929, ('2018-12-24', '19:15:00'): 14145, ('2018-12-24', '19:30:00'): 14359, ('2018-12-24', '19:45:00'): 14548, ('2018-12-24', '20:00:00'): 14740, ('2018-12-24', '20:15:00'): 14971, ('2018-12-24', '20:30:00'): 15199, ('2018-12-24', '20:45:00'): 15423, ('2018-12-24', '21:00:00'): 15644, ('2018-12-24', '21:15:00'): 15885, ('2018-12-24', '21:30:00'): 16124, ('2018-12-24', '21:45:00'): 16369, ('2018-12-24', '22:00:00'): 16424, ('2018-12-24', '22:15:00'): 16615, ('2018-12-24', '22:30:00'): 16798, ('2018-12-24', '22:45:00'): 16967, ('2018-12-24', '23:00:00'): 17138, ('2018-12-24', '23:15:00'): 17300, ('2018-12-24', '23:30:00'): 17466, ('2018-12-24', '23:45:00'): 17634, ('2018-12-25', '00:00:00'): 18459}

In [152]:
df.head()

  delivery_start           timestamp  wind forecast in MW  ID Position
0     2018-12-20 2018-12-20 00:00:00                12815         -513
1     2018-12-20 2018-12-19 23:45:00                12629         -699
2     2018-12-20 2018-12-19 23:30:00                12546         -782
3     2018-12-20 2018-12-19 23:15:00                12654         -674
4     2018-12-20 2018-12-19 23:00:00                12741         -587

In [432]:
df

       delivery_start           timestamp  wind forecast in MW  ID Position
0          2018-12-20 2018-12-20 00:00:00                12815       -11263
1          2018-12-20 2018-12-19 23:45:00                12629       -11449
2          2018-12-20 2018-12-19 23:30:00                12546       -11532
3          2018-12-20 2018-12-19 23:15:00                12654       -11424
4          2018-12-20 2018-12-19 23:00:00                12741       -11337
...               ...                 ...                  ...          ...
368206     2018-12-25 2018-12-24 12:30:00                18217         -242
368207     2018-12-25 2018-12-24 12:15:00                18269         -190
368208     2018-12-25 2018-12-24 12:00:00                18382          -77
368209     2018-12-25 2018-12-24 11:45:00                18458           -1
368210     2018-12-25 2018-12-24 11:30:00                18459            0

[47235 rows x 4 columns]

In [433]:
df.to_csv("./newdata.csv")

In [2]:
def change(x,y): 
    print("no")

In [3]:
def trial(x,y,z): 
    if y.time() in fd[0]

row

In [123]:
def con(x,y,z):  #conv function adds wind power forecast at 11:30 for every delivery date
    if x.time() == ex.time() and x.date != y.date: 
        empty_dict[str(y.date())] = z

In [124]:
df.apply(lambda x: con(x['timestamp'],x['delivery_start'],x['wind forecast in MW']), axis=1)

0         None
1         None
2         None
3         None
4         None
          ...
368206    None
368207    None
368208    None
368209    None
368210    None
Length: 47235, dtype: object

In [125]:
print(empty_dict)

{'2018-12-20': 24078, '2018-12-21': 32517, '2018-12-22': 20828, '2018-12-23': 7937, '2018-12-24': 17634, '2018-12-25': 18459}

In [80]:
df.tail()

       delivery_start           timestamp  wind forecast in MW  ID Position
368206     2018-12-25 2018-12-24 12:30:00                18217         -242
368207     2018-12-25 2018-12-24 12:15:00                18269         -190
368208     2018-12-25 2018-12-24 12:00:00                18382          -77
368209     2018-12-25 2018-12-24 11:45:00                18458           -1
368210     2018-12-25 2018-12-24 11:30:00                18459            0

In [112]:
fd=pd.DataFrame(l)

In [114]:
fd[1]

0      13328
1      13199
2      13069
3      12930
4      12790
       ...
726    18247
727    17466
728    18351
729    17634
730    18459
Name: 1, Length: 731, dtype: int64

In [122]:
df.apply(lambda x: trail(x['timestamp'],x['delivery_start'],x['wind forecast in MW']), axis=1)

NameError: name 'trail' is not defined